version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_OPERATIONS_URL=http://localhost:8080
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true